### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by matiiashuk** [microsoft/PowerBI-visuals-HeatStreams#9]
When the render method is called in an update, a catch occurs with such an error:
"Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings."

**Comment by darthtrevino** [comment]
@matiiashuk Are you using the PowerBI API or the React component? And is this with the released version or the latest on master?

**Comment by matiiashuk** [comment]
This is the latest version on the wizard.  I am using the Powerbi API.  I want to add a context menu when I right-click on a line in Heat Streams that will enable me to display more detailed data, for example, as in the Matrix element.

**Comment by darthtrevino** [comment]
Gotcha, master is still a WIP at this point. I've been updating dependencies and the build system used to package the visual. I'll resolve this once it's ready for the next release cycle

**Comment by darthtrevino** [comment]
@matiiashuk  - this should be resolved in the master branch. If you check out the latest version, there is a storybook containing the React component in isolation. I'm looking into having a new release of the PowerBI visual as well.

I hope that helps!
